# Generated by Django 5.1.7 on 2025-12-29 18:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the movie genre', max_length=100, unique=True, verbose_name='Genre Name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Booking Time')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('booked', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Booking Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Name of the cinema (e.g., Kinopark Esentai)', max_length=200, verbose_name='Cinema Name')),
                ('city', models.CharField(db_index=True, help_text='City where cinema is located', max_length=100, verbose_name='City')),
                ('address', models.CharField(help_text='Street address of the cinema', max_length=255, verbose_name='Address')),
                ('description', models.TextField(blank=True, help_text='Additional information about the cinema', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'ordering': ['city', 'name'],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or number of the hall (e.g., IMAX Hall, Hall 1)', max_length=100, verbose_name='Hall Name')),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats in this hall', verbose_name='Total Seats')),
                ('hall_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('imax', 'IMAX'), ('4dx', '4DX')], default='standard', max_length=50, verbose_name='Hall Type')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='movies.cinema', verbose_name='Cinema')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'ordering': ['cinema', 'name'],
                'unique_together': {('cinema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Movie Title')),
                ('rating', models.FloatField(blank=True, help_text='Movie rating from 0 to 10', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rating')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', verbose_name='Duration')),
                ('description', models.TextField(blank=True, help_text='Movie plot summary', verbose_name='Description')),
                ('language', models.CharField(help_text='Original language of the movie', max_length=50, verbose_name='Language')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/', verbose_name='Poster Image')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('genre', models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='movies.booking', verbose_name='Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Row Number')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Seat Number')),
                ('seat_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('couple', 'Couple Seat')], default='standard', max_length=20, verbose_name='Seat Type')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.hall', verbose_name='Hall')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['hall', 'row', 'number'],
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.seat', verbose_name='Seat'),
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base ticket price in local currency', max_digits=8, verbose_name='Base Price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this showtime is available for booking', verbose_name='Is Active')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.hall', verbose_name='Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Showtime',
                'verbose_name_plural': 'Showtimes',
                'ordering': ['start_time', 'hall'],
                'unique_together': {('hall', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.showtime', verbose_name='Showtime'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('showtime', 'seat')},
        ),
    ]
