# Generated by Django 5.2.8 on 2025-11-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_booking_delete_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'row', 'number')},
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='app.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='app.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Show_time',
        ),
    ]
