# Generated by Django 5.2.7 on 2025-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cinema_created_at_cinema_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='updated_at',
        ),
    ]
