# Generated by Django 5.1.7 on 2025-10-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_time',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='show_time',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
